name: secrets

on: push

jobs:
  build:
    runs-on: ubutunu-latest
    steps:
      - name: learn-github-actions
        env: 
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: main.py
